# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9QisbK7lWUnNP6FeYZsPec6xJ8-MsMp
"""

import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello Thitirat!')

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')